[package]
name = "simple-web-server"
version = "0.1.0"
authors = ["vagrant"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2" #正規表現クレート
lazy_static = "0.2.11"
log = "0.3"